/*
 * This source file was generated by the Gradle 'init' task
 */
package unitconverter;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String input;


        boolean running = true;
        while (running) {
            System.out.println("Unit converter");
            System.out.println("Supports: mm, cm, m, in, ft, yd");
            System.out.println("Format is: [measurement] [starting units] [desired units]");

            input = scanner.nextLine().toLowerCase();
            String[] inputSplit = input.split(" ");
            double units = Double.parseDouble(inputSplit[0]);
            double length_in_mm = 0;

            
            // Unit we are converting FROM
            switch (inputSplit[1]) {
                case "in":
                    length_in_mm = 25.4;
                break;
                case "ft":
                    length_in_mm = 304.8;
                break;
                case "yd":
                    length_in_mm = 914.4;
                break;
                case "mm":
                    length_in_mm = 1;
                break;
                case "cm":
                    length_in_mm = 10;
                break;
                case "m":
                    length_in_mm = 1000;
                break;
                default:
                    System.out.println("Sorry did not understand what unit you are converting from");
                break;
            }

            // Unit we are converting TO
            switch (inputSplit[2]) {
                case "in":
                    units *= length_in_mm / 25.4;
                break;
                case "ft":
                    units *= length_in_mm / 304.8;
                break;
                case "yd":
                    units *= length_in_mm / 914.4;
                break;
                case "mm":
                    units *= length_in_mm / 1;
                break;
                case "cm":
                    units *= length_in_mm / 10;
                break;
                case "m":
                    units *= length_in_mm / 1000;
                break;
                default:
                    System.out.println("Sorry did not understand what unit you are converting to");
                break;
            }

            System.out.println("Your converted value: " + units);


            if (inputSplit[0] == "exit") {
                scanner.close();
                running = false;
            }
            
        }
    }
}